"""Event taxonomy for account-based web analytics."""

EVENT_AUTH_VERIFIED = "auth_verified"
EVENT_AUTH_LOGOUT = "auth_logout"
EVENT_UPLOAD_INTENT_CREATED = "upload_intent_created"
EVENT_UPLOAD_COMPLETED = "upload_completed"
EVENT_DESIGN_JOB_CREATED = "design_job_created"
EVENT_FURNITURE_JOB_CREATED = "furniture_job_created"
EVENT_JOB_COMPLETED = "job_completed"
EVENT_JOB_FAILED = "job_failed"
EVENT_JOB_STALE = "job_stale"
EVENT_CHECKOUT_CREATED = "checkout_created"
EVENT_CHECKOUT_PAID = "checkout_paid"
EVENT_CHECKOUT_REFUNDED = "checkout_refunded"
EVENT_SUPPORT_REQUESTED = "support_requested"
EVENT_PUBLIC_PAGE_VIEW = "public_page_view"
EVENT_PUBLIC_CTA_CLICK = "public_cta_click"
EVENT_CLIENT_PAGE_VIEW = "client_page_view"
EVENT_CLIENT_CTA_CLICK = "client_cta_click"
